### ISSUE TITLE
Error marketeer data

### ISSUE THREAD

**Issue by Anouk2311** [Anouk2311/indeed-job-listings#12]
Hi! I was checking for that error in line 5 of the marketeer data, and I think there is something wrong with the separator. Not sure why, because we did the same with this data set as we did with the others.

<img width="759" alt="Schermafbeelding 2021-03-20 om 09 20 48" src="https://user-images.githubusercontent.com/79919820/111863766-bd8c8980-895d-11eb-814a-2f3427b7bb56.png">

<img width="289" alt="Schermafbeelding 2021-03-20 om 09 20 54" src="https://user-images.githubusercontent.com/79919820/111863770-c2e9d400-895d-11eb-8900-82e57adc91a5.png">

**Comment by GeorgianaHutanu** [comment]
Hi! I just fixed the issue with the separator.
