### ISSUE TITLE
clean data functions

### ISSUE THREAD

**Issue by Anouk2311** [Anouk2311/indeed-job-listings#16]
Hi! I tried to change the clean_data.R file into a file with functions for cleaning the data. However, apparently there are some problems with using dplyr within a function in R. Can one of you take a look at this as well? I don't see how to fix it. Right now, it doesn't create a new column named location_trimmed.

I also included a prototype function to run the cleaning functions on all datasets. But we should first fix that dplyr problem, before testing if this works:
<img width="560" alt="Schermafbeelding 2021-03-23 om 12 21 30" src="https://user-images.githubusercontent.com/79919820/112138861-4dd30480-8bd2-11eb-914a-96a5fb4e6e98.png">

**Comment by Anouk2311** [comment]
Wanted to assign Alan as well but still doesn't work

**Comment by Alantjee** [comment]
I will have a look in R later, what was the error that you got? Maybe that I can find some things on stackoverflow already.

**Comment by ReneeN1998** [comment]
Hi Guys, 

I tried to run it and i got the same error. Have looked on the internet (such as stackoverflow) for a while but i can't seem to find the right solution. 
@Alantjee this is the error i get: 
![image](https://user-images.githubusercontent.com/79910937/112164346-196d4180-8bee-11eb-98ff-d571eeff55f6.png)

**Comment by Alantjee** [comment]
Okay it treats is as an object but it should not be an object as it is only a column. I think that is the problem. I will have a look later in the script if I can fix it.

**Comment by Anouk2311** [comment]
Just found this https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html, maybe it can help

**Comment by Alantjee** [comment]
Hey guys I fixed it, sent a pull request with the new files

**Comment by Alantjee** [comment]
Hey guys I fixed it, sent a pull request with the new files
