### ISSUE TITLE
Create driver object in selenium scraper gives error

### ISSUE THREAD

**Issue by Anouk2311** [Anouk2311/indeed-job-listings#2]
The code we now have is "driver = webdriver.Chrome()". I don't know how it runs on your computers, but I have to put in my path between the brackets, e.g. "driver = webdriver.Chrome('/usr/local/bin/chromedriver')".

Code has to run on all computers without adjustments right?

**Comment by ReneeN1998** [comment]
Hey Anouk, webdriver.Chrome() works for me. Maybe it has to do with the fact you are on a Mac?

**Comment by GeorgianaHutanu** [comment]
Hey Anouk, did you try to put the chromedriver in the Path when editing the environment variables?

**Comment by Anouk2311** [comment]
I think it has to do with Mac. When I remove the path, chromedriver won't start.

@GeorgianaHutanu what do you mean by putting it in the path?
