### ISSUE TITLE
Salary cleaning in cleaning file

### ISSUE THREAD

**Issue by Alantjee** [Anouk2311/indeed-job-listings#20]
Hi Guys, most of the code with functions seem to work so far, only in the cleaning file where I added the salary cleaning step does it go wrong at the salary cleaning function(4th one). If you could have a look as well would be great. Trying to fix it right now but not seeming to get any closer.

**Comment by Anouk2311** [comment]
What exactly goes wrong? As far as I can see if I run it, nothing really happens. It stays per jaar, per maand or per uur.

**Comment by Anouk2311** [comment]
Nvm, that's still the old column. I see what you mean, the numbers in the new column are not correct

**Comment by Anouk2311** [comment]
This was fixed now?
