### ISSUE TITLE
Download data improved file

### ISSUE THREAD

**Issue by Anouk2311** [Anouk2311/indeed-job-listings#23]
Hi! Could you please check if the new download_data.R file works for you? I included functions and it now downloads the data directly from Google Drive instead of Github.

If it works, we can delete all datasets from Github so they are not public anymore.

**Comment by GeorgianaHutanu** [comment]
Hi, It mainly works. For the marketeer data, however, I only get the job listings and for marketing analist I get 20 files instead of 8. Do you know what could be the issue?

**Comment by ReneeN1998** [comment]
Hi, i tried to run it and got the same issues as Georgiana.

**Comment by Anouk2311** [comment]
Ah thanks for testing! Just checked the code and there was a wrong output path for marketeer. I solved it now and uploaded the new file
