### ISSUE TITLE
Data cleaning dirty location goes wrong

### ISSUE THREAD

**Issue by Anouk2311** [Anouk2311/indeed-job-listings#25]
Hi! I was checking the data_clean.R code and our remove_dirty_location also removes 'Noord' from Noord-Holland and Noordwijk so they end up as -holland and wijk. So maybe we should not delete the words first, but directly replace the whole string?

E.g. so replace Amsterdam-noord by Amsterdam, instead of removing noord everywhere.

**Comment by ReneeN1998** [comment]
Hi Anouk, good idea! I did not notice before that it also removes things such as Noord-Holland (which actually makes a lot of sense). It will probably also removes things like Noord-Brabant right? 

Do you need any help with changing it or are you okay with it?

**Comment by Alantjee** [comment]
Yeah true, let's remove all the noord and zuid etc which are not in capital letters and with capital letters in combination with a - replace the entire string

**Comment by Alantjee** [comment]
I replaced it in the code.   Will update to git soon.

**Comment by Alantjee** [comment]
solved it
