### ISSUE TITLE
Documentation for ODCM is completely done, Readme needs additions

### ISSUE THREAD

**Issue by ReneeN1998** [Anouk2311/indeed-job-listings#26]
Hey guys, 

The documentation (datasheet) for ODCM is imo completely done, please do have a look before the deadline to make any enhancements or changes. 

Readme file has already been filled in for the most, still needs the part where we explain how to run exactly. I will start working on that. Maybe a good idea to shorten the Method & Results part a little bit? Makes it easier to read.

**Comment by Alantjee** [comment]
Yeah we can maybe add some of the readme part into the results section of the "paper"

**Comment by GeorgianaHutanu** [comment]
I had a read of both and I implemented some minor changes. Readme still needs to be completed.

**Comment by Anouk2311** [comment]
Are we keeping 2.13 2.14 and 2.15 in our documentation? Since it says they can be skipped, should we just delete them? Or still keep them like we have now

**Comment by Anouk2311** [comment]
Also made some small changes but I think the odcm documentation is completely finished now

**Comment by ReneeN1998** [comment]
Only thing left to do is adding summary stats in the ODCM documentation and than it is done!

**Comment by Anouk2311** [comment]
Im having a look at it right now!

**Comment by Anouk2311** [comment]
ODCM documentation is completely finished
