### ISSUE TITLE
download_data issue

### ISSUE THREAD

**Issue by GeorgianaHutanu** [Anouk2311/indeed-job-listings#29]
Hi guys, I just tested download_data.R and it seems that there is still an issue for the marketing-analist data, I only get the listings and the first 3 descriptions. Can you have a look at it?

**Comment by Anouk2311** [comment]
For me it downloads everything. Are others having an issue with downloading the files as well?

**Comment by GeorgianaHutanu** [comment]
Now it works perfectly for me as well!
