### ISSUE TITLE
Scraper loops over the first 80 pages only

### ISSUE THREAD

**Issue by Anouk2311** [Anouk2311/indeed-job-listings#3]
Do we only want to scrape 80 pages? Or all available job listings?

**Comment by ReneeN1998** [comment]
Preferably all the pages right?

**Comment by GeorgianaHutanu** [comment]
Yes, in the page loop (example: for i in range(0,800,10)) set the '800' according to how many pages are available for the job search in the specific date that you're scraping. To find out how many pages are available, go manually on the last page of the website and inspect the url. Hope this helps.

**Comment by Anouk2311** [comment]
But do we want to check that manually? There should be a way to make sure it always loops through all available pages right?
