### ISSUE TITLE
Last things Readme

### ISSUE THREAD

**Issue by ReneeN1998** [Anouk2311/indeed-job-listings#38]
- Update the repository overview <-- I'll pick that up
- Integrate analysis salary part in the results overview <-- I'll pick it up when salary analyses is fixed 
- Should we give a description on how to run the makefile? Or is that 'common sense'
- Overall read through and last checks

Almost done! Great job everyone :)

**Comment by Alantjee** [comment]
I added the salary analysis part in the readme

**Comment by ReneeN1998** [comment]
added the last packages to install and final repo overview

**Comment by Anouk2311** [comment]
Just read through it as a last check and I think the readme is done!

**Comment by GeorgianaHutanu** [comment]
Same, I changed minor things but I think it's done.
