### ISSUE TITLE
Switching of the review/location

### ISSUE THREAD

**Issue by ReneeN1998** [Anouk2311/indeed-job-listings#4]
Hey guys, at the #getjoblocation part and #getcompanyreview part in the scraper the locations and the reviews get mixed up with eachother. I think i found the problem, but i don't know how to fix it. Could one of you have a look at it? See the pictures. The text.splitlines()[1] gives the reviews in this case and text.splitlines()[2] gives the location. 

This is why these 2 get mixed up, because not every vacancy has a review component. 

![image](https://user-images.githubusercontent.com/79910937/110946174-db933200-833e-11eb-8aef-d4aae8e9b135.png)
![image](https://user-images.githubusercontent.com/79910937/110946619-5f4d1e80-833f-11eb-980f-7d636814ff97.png)

**Comment by GeorgianaHutanu** [comment]
Hey, I rewrote the code into 3 alternatives, and in my experience the first one is the fastest and gives the least missing data. Please have a look in the data folder at postings_13.03.21.csv and descriptions_13.03.21.csv. Let me know which alternative you find best.
