### ISSUE TITLE
Combined plot salary analysis

### ISSUE THREAD

**Issue by Alantjee** [Anouk2311/indeed-job-listings#45]
Our combined plot for the salary analysis for top locations salary wise only shows 3 cities because they are the only 3 cities that show up in all 4 plots. If we relax the filter of 3 job postings per location we will get a plot with more cities in it but some of these cities will have only one job ad per search term and thus an average is not very useful in this case.

What do you guys want, keep the plots like this with only a few cities to be compared, or remove the minimum number of job ads needed per location to get plots with more cities in the plot but single job ads having higher influence on average salaries.

**Comment by ReneeN1998** [comment]
Hi Alan, i would prefer to keep the plots like this. We can't say anything about a city with only one or few job ads. That won't be a top location in my opinion and it would manipulate the other cities too much.

**Comment by Anouk2311** [comment]
I agree with Renée. As long as we mention in the text why it only has 3 locations it should be fine
