### ISSUE TITLE
How to name ambiguous location strings

### ISSUE THREAD

**Issue by Alantjee** [Anouk2311/indeed-job-listings#46]
We know give the name Unknown to all locations that are not in a specific city. Should we maybe change this to Remote or Online or something similar?

**Comment by ReneeN1998** [comment]
Yes online seems a good solution to me.

**Comment by Anouk2311** [comment]
They are called online now? Because then we should also change that in the analysis.rmd text. It now says remote there

**Comment by GeorgianaHutanu** [comment]
I just checked and I think all changes are implemented.
